### PR TITLE
Split readme into two docs, one for users, one for contributors

### LINKED ISSUE #83: Document the developer installation details

### PR DESCRIPTION
**Pull request by joshski**
Reviewers please! (especially helpful would be reviewers who are not so familiar with the project)

I've followed @EmmaJP's idea of splitting into two guides and leaving the readme as more of a signpost...

Probably best to ignore the diff on this one, just read this and see if it makes sense: https://github.com/cucumber-ltd/bbc-a11y/blob/better-docs/README.md

Fixes #83 and #89

### CODE REVIEW

**Comment by greenc05** [comment]
It would be nice to have a path to the standards so people know where to find the names of them to add for skipping @joshski

**Comment by greenc05** [comment]
Is there a way to skip a standard for a list of urls or to I need to add it to every url @joshski?

**Comment by greenc05** [comment]
Sorry me again, is there a way of running just one standard or would you just have to list out all of them in the skip except for the one you want to run @joshski?

**Comment by joshski** [comment]
Hi @greenc05, thanks!

This PR is just about improving the documentation for the existing features and installation process. Would you mind making other issues for these other bits:

* a way to skip a standard for a list of urls
* a way of running just one standard

Both of these are quick things to fix, but they aren't documented because they haven't been implemented yet.

**Comment by greenc05** [comment]
Sure wasn't quite sure where to ask my questions, will do that now @joshski

**Pull request merged**
