### PR TITLE
Adding Rough Feature Files for all BBC accessibility guidelines 

### PR DESCRIPTION
**Pull request by Shashikant86**
@mattwynne Just sorting out feature files and step_definitions to automate all possible accessibility standards. Let me know what you think abut this approach.

### CODE REVIEW

**Comment by mattwynne** [comment]
Hi @Shashikant86, thanks for mucking in to help with this!

I think before we race ahead and convert more of the standards to features, we should address this: https://github.com/cucumber-ltd/bbc-a11y/issues/29

If you're interested in getting more involved, maybe we can arrange to do some pairing on the project when I'm next in at the BBC?

**Comment by Shashikant86** [comment]
@mattwynne sure, I have done bit of research on how to automate rest of the standards. We will definitely pair on this and I am happy to contribute to BBC-a11y. I am attending your workshop on 30th in White City. See you there then

**Comment by joshski** [comment]
Hi @Shashikant86, looks like this is pretty out of date with where the code is now, so I'm going to close this issue. Please reopen with a comment if you disagree.

**Comment by EmmaJP** [comment]
@joshski there are currently 10 feature files under check_standards and 21 HTML accessibility standards (http://www.bbc.co.uk/guidelines/futuremedia/accessibility/html/).  The code Shashi created may no longer be correct, but is the intention of this (a feature file for each standard) being fulfilled via any other issues raised?  #36 - #40 are about automating a few, but that is not the same.

**Pull request closed without merging**
